version: "3.8"

networks:
  tiket-network:
    driver: bridge
    name: tiket-network

# services
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    networks:
      - tiket-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

      # services jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    networks:
      - tiket-network
    ports:
      - target: 16686
        published: 16686
        protocol: tcp
        mode: host

  # my service
  tiketdotcom:
    build: .
    container_name: tiketdotcom
    ports:
      - target: 7010
        published: 7010
        protocol: tcp
        mode: host
    networks:
      - tiket-network
    depends_on:
      - mysqldb
      - jaeger
    environment:
      - DATABASE_HOST=mysqldb
      - JAEGER_HOST=jaeger
